Development <- Dev-IMJ
lmbek/2d-pingpong-with-gobek-and-three-js pull request #3
Opened 2023-01-03 17:56 UTC by notHooman996

2023-01-04 23:57 UTC, NineNineFive requested changes
Få ændringer tilføjes og så kan den merges

2023-01-04 23:57 UTC, NineNineFive commented on frontend/ball.js
> +    yVelocity = 0
lad os omstrukturere xVelocity og yVelocity, så de istedet er lokale konstanter i setInitialMovement

2023-01-04 23:57 UTC, NineNineFive commented on frontend/wall.js
> +    constructor(yPosition) {
Er der en grund til at vi kun har y position og ikke x position? - Hvor starter x fra? 
- Kan være vi skal have en kommentar til klassen øverst der forklarer Wall objektet. Fylder den hele bredden ud?

2023-01-05 12:13 UTC, notHooman996 commented on frontend/ball.js
> +    yVelocity = 0
xVelocity og yVelocity anvendes flere steder, og ikke kun i metoden setInitialMovement. Derfor skal de være i field.

2023-01-05 12:17 UTC, notHooman996 commented on frontend/wall.js
> +    constructor(yPosition) {
Ja, der skal nok være en forklaring i starten af klassen. Variablen yPosition bliver sat når man kalder på klassen gennem constructor, altså når det bliver instantieret. Grunden til at det kun er yPosition, er fordi en væg i PingPong kun er i toppen og bunden af scenen, derfor er det kun nødvendigt at sætte yPosition. En væg fylder hele bredden ud, hvilket er defineret i klassen Wall via væggens mesh. Denne mesh har i x komponent x = window.innerWidth

2023-01-05 23:22 UTC, lmbek commented on frontend/ball.js
> +    yVelocity = 0
okay vi finder en anden løsning så, jeg tager mig af refactoring delen for denne :)

2023-01-05 23:28 UTC, NineNineFive approved these changes
godkendt godt arbejde, jeg laver nok lidt refactoring på min version. Så må vi se om der opstår en konflikt, jeg skal nok håndtere, hvis der gør

2023-01-05 23:29 UTC, merged